### ISSUE TITLE
Learn Springboot

### ISSUE THREAD

**Issue by Jeoml** [Jeoml/Jeoml#7]
https://www.youtube.com/watch?v=Nv2DERaMx-4

**Comment by Musabhaqqani** [comment]
https://www.youtube.com/watch?v=c3gKseNAs9w

This is a shorter version.

**Comment by Musabhaqqani** [comment]
Spring: The Spring Framework provides a comprehensive programming and configuration model for modern Java-based enterprise applications - on any kind of deployment platform.

A key element of Spring is infrastructural support at the application level: Spring focuses on the "plumbing" of enterprise applications so that teams can focus on application-level business logic, without unnecessary ties to specific deployment environments.

Spring Boot, is built on the spring framework, this new integration helps to develop apps faster and manage dependencies easily. Springboot provides a way to group all the services (configurations) into a starter template. You don't need to make the configuration, it is already given as a started template.
Easier to create micro services and it is ready to deploy as it generates a .jar file.

**Comment by Musabhaqqani** [comment]
mvn spring-boot:run

**Comment by Musabhaqqani** [comment]
Integrated H2 database, to access, hit /h2-console in the url.

**Comment by Musabhaqqani** [comment]
### Spring applications must always contain these three layers,
**1.Presentation Layer:**
Handles user interaction, typically through web interfaces (REST controllers, JSP pages, Thymeleaf templates, etc.).
Responsible for authentication, authorization, and JSON translation.
Uses Spring MVC or Spring WebFlux for web development.

**2.Business Layer (Service Layer):**
Contains the core business logic of the application.
Handles data validation, business rules, and calculations.
Orchestrates the flow of data between the presentation and persistence layers.
Uses Spring annotations like @Service to define service classes. 

**3.Persistence Layer (Repository Layer):**
Interacts with the database or other data sources.
Performs CRUD (Create, Read, Update, Delete) operations on data.
Uses Spring Data JPA or other data access frameworks to simplify data access.
Uses Spring annotations like @Repository to define repository interfaces.

**4.Database Layer:**
Represents the actual database system (e.g., MySQL, PostgreSQL, MongoDB).
Stores the application's data.

**Comment by Musabhaqqani** [comment]
https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html
JPA repository documentation.

**Comment by Musabhaqqani** [comment]
![Screenshot 2024-08-01 112912](https://github.com/user-attachments/assets/ddb3bdd3-de52-417b-a37c-5e2c1aeccbf1)


javax.validation.
Hibernate-validation.
Have alot of functionalities like regular expressions and alot more, read the docs as required.

**Comment by Musabhaqqani** [comment]
Learn how to pass exceptions from a better source, RestResponseExceptionHandler
